### ISSUE TITLE
what is used on windows?

### ISSUE THREAD

**Issue by beppe9000** [webcamoid/akvcam#11]

**Comment by ghost** [comment]
Wants to cheat the teacher of online class? 2333

**Comment by hipersayanX** [comment]
What? :confused: 

![visible](https://user-images.githubusercontent.com/1249885/77570868-307a3600-6eab-11ea-9752-3b8cd13603d8.jpg)

**Comment by hipersayanX** [comment]
If you mean if this driver can be used in Windows, no, this is a GNU/Linux only driver.
Webcamoid already integrates it's own [virtual camera for Windows](https://github.com/webcamoid/webcamoid/tree/master/libAvKys/Plugins/VirtualCamera/src/dshow/VirtualCamera).

**Comment by beppe9000** [comment]
> Webcamoid already integrates it's own [virtual camera for Windows](https://github.com/webcamoid/webcamoid/tree/master/libAvKys/Plugins/VirtualCamera/src/dshow/VirtualCamera).

This. I was looking for `AkVCamAssistant.exe`'s sources. Thakns
