### ISSUE TITLE
Can't install in archlinux

### ISSUE THREAD

**Issue by djemilbakhti** [webcamoid/akvcam#3]
archlinux : 
kernel 5.0:

make -C /usr/lib/modules/5.0.0-arch1-1-ARCH/build M=/tmp/src  modules
make[1]: Entering directory '/usr/lib/modules/5.0.0-arch1-1-ARCH/build'
  CC [M]  /tmp/src/module.o
  CC [M]  /tmp/src/attributes.o
  CC [M]  /tmp/src/buffer.o
  CC [M]  /tmp/src/buffers.o
/tmp/src/buffers.c: In function ‘akvcam_buffers_dequeue’:
/tmp/src/buffers.c:488:9: error: implicit declaration of function ‘do_gettimeofday’; did you mean ‘do_settimeofday64’? [-Werror=implicit-function-declaration]
         do_gettimeofday(&v4l2_buff->timestamp);
         ^~~~~~~~~~~~~~~
         do_settimeofday64
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:277: /tmp/src/buffers.o] Error 1
make[1]: *** [Makefile:1553: _module_/tmp/src] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.0.0-arch1-1-ARCH/build'
make: *** [Makefile:42: all] Error 2

**Comment by hipersayanX** [comment]
Fixed
