### ISSUE TITLE
Error creating the virtual camera

### ISSUE THREAD

**Issue by BurningCayenne** [webcamoid/akvcam#32]
When I try to load the driver, it gives me an error. Here is the full input and output: 

`$ sudo modprobe videodev`
`$ sudo insmod akvcam.ko`
`insmod: ERROR: could not insert module akvcam.ko: Operation not permitted`

Thanks for reading, any help would be apreciated

**Comment by hipersayanX** [comment]
Recompile akvcam and try loading again, if that does not works give me the [dmesg log](https://github.com/webcamoid/akvcam/wiki/Debugging-the-driver).

**Comment by hipersayanX** [comment]
No answer, closing.
