### ISSUE TITLE
Having an issue installing the driver

### ISSUE THREAD

**Issue by HishamLadha** [webcamoid/akvcam#35]
Hey, it's me again. I installed Webcamoid without any problems but wanted to install akvcam to use webcamoid as a virtual camera on zoom (custom filters and all). I tried installing akvcam but every time I try it does not show up after running this command `ls /lib/modules/$(uname -r)/extra/akvcam.ko*`. I even checked the folder manually and the driver is not there. I installed akvcam inside this directory: /home/user/Webcamoid/akvcam then used the make and make install which seemed to run successfully, but it still does not show up. Any solution to this?

**Comment by hipersayanX** [comment]
I've updated the wiki, and will upload the installer once Travis CI trigger the build.
