### ISSUE TITLE
[issue] Cannot create new device

### ISSUE THREAD

**Issue by tuapuikia** [webcamoid/akvcam#38]
I compiled the latest kernel code and install it using modprobe command. Below is the dmesg output

Version : git commit bfe8549fbb4cb9f67e2da1f648efcaff7413e137
OS : Ubuntu Focal
Kernel : 5.9.8

[342526.129736] [akvcam] driver.c(75): Initializing driver
[342526.129738] [akvcam] driver.c(83): Reading settings
[342526.129842] Can't read device formats
[342526.129851] Can't read device formats
[342526.129856] [akvcam] driver.c(618): No devices found

Output of the config.ini

cat /etc/akvcam/config.ini 
[Cameras]
cameras/size = 2

cameras/1/type = output
cameras/1/mode = mmap, userptr, rw
cameras/1/description = Virtual Camera (output device)
cameras/1/formats = RGB24
cameras/1/videonr = 7

cameras/2/type = capture
cameras/2/mode = mmap, rw
cameras/2/description = Virtual Camera
cameras/2/formats = RGB32, RGB24
cameras/1/videonr = 9

**Comment by hipersayanX** [comment]
You haven't defined the [formats](https://github.com/webcamoid/akvcam/wiki/Configure-the-cameras#defining-the-formats).
