### ISSUE TITLE
using akvcam with qemu

### ISSUE THREAD

**Issue by promeneur** [webcamoid/akvcam#50]
Hello

Is there a way to use an akvcam  webcam with a qemu virtual machine ?

I assume this needs the akvcam to emulate an usb webcam with a vendoreid and a productid or something else.

Thanks

**Comment by hipersayanX** [comment]
From host to guest? afaik, no, qemu doesn't seems to have any option for bypassing a v4l2 device. In theory, it would be possible to make it work there writing the functions to make it work as an [USB Gadget](https://www.kernel.org/doc/html/latest/driver-api/usb/gadget.html), but don't expect it in the (not even) near time.
But if you want something like that, akvcam works pretty fine in VirtualBox.

**Comment by promeneur** [comment]
Thanks
