### ISSUE TITLE
Cannot find it.

### ISSUE THREAD

**Issue by TheStrefo** [webcamoid/akvcam#51]
After downloading and running the installer attached, I couldn't find the akvcam anywhere on my computer. I search by using a camera app to try to find a camera device, it didn't work. Same thing happened when I tried to search for it using discord.

**Comment by hipersayanX** [comment]
It should be located at _/opt/akvcam-1.2.0_ and a symlink in _/usr/src/akvcam-1.2.0_ pointing to _/opt/akvcam-1.2.0/src_.
