### ISSUE TITLE
Makefile doesn't seem to be working right?

### ISSUE THREAD

**Issue by funcyChaos** [webcamoid/akvcam#52]
I've had a couple problems with  make files lately, so maybe I'm the problem lol

getting this result for sudo make dkms_install

dkms remove akvcam/1.2.0 --all
make: dkms: Command not found
make: [Makefile:63: dkms_uninstall] Error 127 (ignored)
rm -rvf /usr/src/akvcam-1.2.0
rm -rvf /usr/src/akvcam-1.2.0
mkdir -p /usr/src/akvcam-1.2.0
cp -f Makefile /usr/src/akvcam-1.2.0
cp -f dkms.conf /usr/src/akvcam-1.2.0
cp -f *.h /usr/src/akvcam-1.2.0
cp -f *.c /usr/src/akvcam-1.2.0
dkms install akvcam/1.2.0
make: dkms: Command not found
make: *** [Makefile:57: dkms_install] Error 127

**Comment by hipersayanX** [comment]
As the error says, you must install dkms.

**Comment by funcyChaos** [comment]
ok.
