### ISSUE TITLE
The example for `/etc/akvcam/config.ini` may be wrong in wiki

### ISSUE THREAD

**Issue by AkkyOrz** [webcamoid/akvcam#56]
This is [the example in wiki](https://github.com/webcamoid/akvcam/wiki/Configure-the-cameras#defining-the-devices).

```
[Cameras]
cameras/size = 2

cameras/1/type = output
cameras/1/mode = mmap, userptr, rw
cameras/1/description = Virtual Camera (output device)
cameras/1/formats = 2
cameras/1/videonr = 7

cameras/2/type = capture
cameras/2/mode = mmap, rw
cameras/2/description = Virtual Camera
cameras/2/formats = 1, 2
cameras/1/videonr = 9
```

However, the last line, `cameras/1/videonr = 9`, looks wrong.
I think that `cameras/2/videonr = 9` will be correct.
I've tried editing this wiki, but I don't know how to edit wiki page.
So I'd like you to check this issue.
Thank you.

**Comment by hipersayanX** [comment]
Fixed, thanks!
