### ISSUE TITLE
akvcam-1.2.2 can't be installed - can' find linux-headers

### ISSUE THREAD

**Issue by fancywriter** [webcamoid/akvcam#62]
Hello!

Trying to install akvcam-1.2.2, it's complaining that linux-headers isn't installed:
> The following dependencies are missing: linux-headers. Install them and try again

But it is installed (5.15, Gentoo).

Where does akvcam try to find it?

**Comment by hipersayanX** [comment]
[Here](https://github.com/webcamoid/akvcam/blob/35e89214df2960ff570b93e15df7fd740d5fede5/ports/deploy/installscript.posix.qs#L5) is the code for the installer, the kernel headers should be at ```/lib/modules/$(uname -r)/build```.

**Comment by fancywriter** [comment]
That's weird... it is there.
```
$ cat /lib/modules/$(uname -r)/build/include/generated/uapi/linux/version.h
#define LINUX_VERSION_CODE 331552
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
#define LINUX_VERSION_MAJOR 5
#define LINUX_VERSION_PATCHLEVEL 15
#define LINUX_VERSION_SUBLEVEL 32
```

**Comment by hipersayanX** [comment]
I've tested, and its working fine for me and the code is correct, maybe its a bug in QtIFW or something else. Try installing it [manually](https://github.com/webcamoid/akvcam/wiki/Build-and-install).

**Comment by hipersayanX** [comment]
Issue not reproducible with 1.2.3, closing.
