### ISSUE TITLE
error building on kernel 6.7

### ISSUE THREAD

**Issue by silverhikari** [webcamoid/akvcam#80]
akvcam Version: git commit  3996065
gcc Version: 13.2.1

<details>
<summary>DKMS make.log</summary>
<pre>
 DKMS make.log for akvcam-1.2.4.r5.g3996065 for kernel 6.7.0-0-MANJARO (x86_64)
   2   │ Sun Jan 21 04:19:31 PM EST 2024
   3   │ make -C /usr/lib/modules/6.7.0-0-MANJARO/build M=/var/lib/dkms/akvcam/1.2.4.r5.g3996065/build  modules
   4   │ make[1]: Entering directory '/usr/lib/modules/6.7.0-0-MANJARO/build'
   5   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/module.o
   6   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/attributes.o
   7   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/buffers.o
   8   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/controls.o
   9   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/device.o
  10   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/driver.o
  11   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/file_read.o
  12   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/format.o
  13   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/frame.o
  14   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/frame_filter.o
  15   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/ioctl.o
  16   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/list.o
  17   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/log.o
  18   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/map.o
  19   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/rbuffer.o
  20   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/settings.o
  21   │   CC [M]  /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/utils.o
  22   │ /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/device.c: In function ‘akvcam_device_new’:
  23   │ /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/device.c:133:14: error: ‘V4L2_DEVICE_NAME_SIZE’ undeclared (first use in this function)
  24   │   133 |              V4L2_DEVICE_NAME_SIZE,
  25   │       |              ^~~~~~~~~~~~~~~~~~~~~
  26   │ /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/device.c:133:14: note: each undeclared identifier is reported only once for each function it 
       │ appears in
  27   │ make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build/device.o] Error 1
  28   │ make[3]: *** Waiting for unfinished jobs....
  29   │ make[2]: *** [/usr/lib/modules/6.7.0-0-MANJARO/build/Makefile:1911: /var/lib/dkms/akvcam/1.2.4.r5.g3996065/build] Error 2
  30   │ make[1]: *** [Makefile:234: __sub-make] Error 2
  31   │ make[1]: Leaving directory '/usr/lib/modules/6.7.0-0-MANJARO/build'
  32   │ make: *** [Makefile:44: all] Error 2
</pre>
</details>

**Comment by hipersayanX** [comment]
Fixed with latest release.
